<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlayButton</name>
   <tag></tag>
   <elementGuidId>6ee94166-125e-4fd1-bc04-0bb2fd6abee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//tp-yt-paper-button[@id='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.yt-simple-endpoint.style-scope.yt-button-renderer > #button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tp-yt-paper-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-button-renderer style-dark-on-white size-default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elevation</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Shuffle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shuffle
    

    
    
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-page&quot;)/div[@id=&quot;header&quot;]/ytmusic-immersive-header-renderer[@class=&quot;style-scope ytmusic-browse-response&quot;]/div[@class=&quot;content-container-wrapper style-scope ytmusic-immersive-header-renderer&quot;]/div[@class=&quot;gradient-container style-scope ytmusic-immersive-header-renderer&quot;]/div[@class=&quot;content-container style-scope ytmusic-immersive-header-renderer&quot;]/div[@class=&quot;actions style-scope ytmusic-immersive-header-renderer&quot;]/div[@class=&quot;buttons style-scope ytmusic-immersive-header-renderer&quot;]/div[@class=&quot;play-buttons style-scope ytmusic-immersive-header-renderer&quot;]/yt-button-renderer[@class=&quot;play-button style-scope ytmusic-immersive-header-renderer style-dark-on-white size-default&quot;]/a[@class=&quot;yt-simple-endpoint style-scope yt-button-renderer&quot;]/tp-yt-paper-button[@id=&quot;button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//tp-yt-paper-button[@id='button'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/ytmusic-immersive-header-renderer/div/div/div/div[2]/div/div/yt-button-renderer/a/tp-yt-paper-button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::tp-yt-paper-button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bruno Mars'])[1]/following::tp-yt-paper-button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio'])[1]/preceding::tp-yt-paper-button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//yt-button-renderer/a/tp-yt-paper-button</value>
   </webElementXpaths>
</WebElementEntity>
