<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonPlay</name>
   <tag></tag>
   <elementGuidId>156e69d6-a914-4ef2-9f08-24bb989d33c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ytmusic-play-button-renderer[@id='play-button']/div/yt-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>yt-icon.icon.style-scope.ytmusic-play-button-renderer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon style-scope ytmusic-play-button-renderer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-page&quot;)/ytmusic-section-list-renderer[@class=&quot;style-scope ytmusic-browse-response&quot;]/div[@id=&quot;contents&quot;]/ytmusic-immersive-carousel-shelf-renderer[@class=&quot;style-scope ytmusic-section-list-renderer fullbleed&quot;]/div[@class=&quot;background-gradient style-scope ytmusic-immersive-carousel-shelf-renderer&quot;]/ytmusic-carousel[@class=&quot;carousel style-scope ytmusic-immersive-carousel-shelf-renderer&quot;]/div[@id=&quot;items-wrapper&quot;]/ul[@id=&quot;items&quot;]/ytmusic-two-row-item-renderer[@class=&quot;style-scope ytmusic-carousel&quot;]/a[@class=&quot;yt-simple-endpoint image-wrapper style-scope ytmusic-two-row-item-renderer&quot;]/ytmusic-item-thumbnail-overlay-renderer[@class=&quot;thumbnail-overlay style-scope ytmusic-two-row-item-renderer&quot;]/div[@id=&quot;content&quot;]/ytmusic-play-button-renderer[@id=&quot;play-button&quot;]/div[@class=&quot;content-wrapper style-scope ytmusic-play-button-renderer&quot;]/yt-icon[@class=&quot;icon style-scope ytmusic-play-button-renderer&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ytmusic-play-button-renderer[@id='play-button']/div/yt-icon</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::yt-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::yt-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halloween Hits'])[1]/preceding::yt-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sam The Sham And The Pharaohs'])[1]/preceding::yt-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/yt-icon</value>
   </webElementXpaths>
</WebElementEntity>
